### ISSUE TITLE
Save ReproZip Output

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/wt-prov-model#16]
@tmcphillips 
Since these are solid examples I think that we should include the ReproZip output for any curious minds. It may also be useful to point to ReproZip output in a meeting where we wouldn't want to run the container.

If it's fine with you, I should be able to figure out how to do this.

**Comment by tmcphillips** [comment]
The files appear and remain in the reprozip-trace/ subdirectory of each example when the examples are run, but currently are hidden from Git (`examples/.gitignore`).  

I've been excluding them because the SQLite file and the JSON file both contain information that will differ from run to run of the same example (e.g. timestamps).  So anyone who clones the repo, runs the examples, and does `git diff` will see both files differ for every example.

These differences are of little use, whereas differences in the various datalog fact files (which mask out the timestamps) and visualizations that are generated generally can be meaningful. (Although some trivial variation is observed, the less meaningful differences are easy to spot by eye.)  I use this feature as a (lazy-developer's) test-everything-integration-test after I change anything (i.e several times per hour and always just before any commit).  

Also, for significant examples, the two ReproZip trace files may start to get large (along with the diffs of the binary SQLite file), so the size of the repo will grow a bit faster if we include them.

What do you think?

**Comment by ThomasThelen** [comment]
Agreed that the extra files can get quite large (and the repo is a good size already). I think a better example would be for me to add some of these examples to the [provenance-examples](https://github.com/whole-tale/provenance-examples) repo. The stuff there is meant to be used as a reference which might make it more appropriate place!
